version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - yarn generate:migration
      - yarn prisma:generate
      - yarn build

artifacts:
  base-directory: backend
  files:
    - "**/*"
