version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - yarn build
      - cd ../

artifacts:
  base-directory: .
  files:
    - backend/node_modules/**/*
    - backend/dist/**/*
    - backend/prisma/**/*
    - backend/package.json
    - shared/**/*
  discard-paths: yes
