version: 0.2

env:
  variables:
    DATABASE_URL: postgresql://postgres.rwhnkwotaizeytuegewy:JtBeUzjbi49wtIzl@aws-0-eu-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
    DIRECT_URL: postgresql://postgres.rwhnkwotaizeytuegewy:JtBeUzjbi49wtIzl@aws-0-eu-west-2.pooler.supabase.com:5432/postgres

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - yarn generate:migration
      - yarn prisma:generate
      - yarn build

artifacts:
  base-directory: backend
  files:
    - "**/*"
