version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - yarn build
      - cd ../

artifacts:
  base-directory: backend
  files:
    - node_modules/**/*
    - dist/**/*
    - prisma/**/*
    - package.json
    - shared/**/*
