version: 0.2

phases:
  install:
    commands:
      - echo Entering backend directory...
      - cd backend
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Entering backend directory...
      - cd backend
      - echo Building application...
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: backend
  discard-paths: yes
