version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Node.js 20 manually in pre_build..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - node -v
      - npm -v

  install:
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - cd backend
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: backend
  discard-paths: yes
