version: 0.2

phases:
  install:
    commands:
      - echo "Entering backend directory..."
      - cd backend
      - yarn install

  build:
    commands:
      - cd backend
      - yarn build

artifacts:
  base-directory: backend
  files:
    - "**/*"
    - "!yarn.lock" # Exclude yarn.lock file
  discard-paths: yes
