version: 0.2

cache:
  paths:
    - node_modules/**/*
    - apps/backend/node_modules/**/*
    - packages/shared/node_modules/**/*

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Installing all workspace deps"
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo "🚀 Building backend + shared"
      - yarn build:be

  post_build:
    commands:
      - echo "🔧 Installing production deps in apps/backend"
      - cd apps/backend
      - pwd
      - ls -al
      - cat package.json
      - rm -rf node_modules
      - yarn install
      - echo "📦 Zipping artifact"
      - zip -r ../../backend-deploy.zip dist node_modules package.json yarn.lock

artifacts:
  files:
    - backend-deploy.zip
