version: 0.2

cache:
  paths:
    - node_modules/**/*
    - apps/backend/node_modules/**/*
    - packages/shared/node_modules/**/*

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Installing all workspace deps"
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo "🚀 Building backend + shared"
      - yarn build:be
      - echo "🧹 Cleaning out all node_modules"
      - rm -rf node_modules apps/backend/node_modules

  post_build:
    commands:
      - echo "🔧 Installing production deps"
      - yarn install --production
      - cp -r apps/backend/dist ./dist
      - cp apps/backend/package.json ./package.json
      - cp -a apps/backend/node_modules/. node_modules/
      - echo "📦 Zipping artifact"
      - zip -r backend-deploy.zip dist node_modules package.json yarn.lock

artifacts:
  files:
    - backend-deploy.zip
